# The job itself
# Escort + ERPer + touchytouchy
- type: job
  id: Escort
  name: job-name-escort
  description: job-description-escort
  playTimeTracker: JobEscort
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # frontier: 24 hrs / 4 shifts | CS: 12 hours / 2 shifts
    - !type:RoleTimeRequirement
      role: JobPirate
      time: 3600 # CS: 1 hour
#    - !type:DepartmentTimeRequirement # CS: swaps the playtime requirement to literally just be an hour of the role itself.
#      department: Security
#      time: 10800 # 3 hrs
  startingGear: EscortGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconBoxer"
  supervisors: job-supervisors-freebooters-union
  weight: 40
  displayWeight: 3
  setPreference: true
  newPlayerMessage: false
  access:
  - Pirate
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
#    - type: AutoPirate
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: FalseRecord
    - type: DisableSuitSensors
    - type: IsPirate
  - !type:AddRpiJobModifierSpecial
    modifiersToAdd:
    - rpiJobModifierPirate
  - !type:AddRpiAuraSpecial
    aurasToAdd:
    - rpiAuraMassageTherapist
  - !type:RpiChatJudgementModifierSpecial
    modsToAdd:
    - rpiChatJudgementModifierMassageTherapist
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant, FreedomImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

#play time tracker
- type: playTimeTracker
  id: JobEscort

- type: entity
  id: SpawnPointEscort
  parent: SpawnPointJobBase
  name: escort spawn point
  suffix: Frontier
  components:
  - type: SpawnPoint
    job_id: Escort
  - type: Sprite
    sprite: Structures/Decoration/banner.rsi
    state: banner-red

- type: startingGear
  id: EscortGear
  equipment:
    belt: ClothingBeltUtility
  storage:
    back:
    - EncryptionKeyFreelance
    - ShipVoucherCoyoteEscort
    - ComputerIFFFlatpack

- type: chameleonOutfit
  id: EscortChameleonOutfit
  job: Escort
  equipment:
    head: ClothingHeadHatChef
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskItalianMoustache
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterJacketChef
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesChef

- type: roleLoadout
  id: JobEscort
  groups:
  - PilotHead
  #  - NFPirateNeck
  - PilotNeck #Coyote: Pirate Loadout Expansion
  - PilotJumpsuit
  #  - NFPirateGloves
  - MercenaryGloves #Coyote: Pirate Loadout Expansion
  - PilotBackpack
  - PilotForcedOuterClothing
  - MercenaryOuterClothing #Coyote: Pirate Loadout Expansion
  - MercenaryShoes
  - PilotFace
  - MercenaryGlasses #Coyote: Pirate Loadout Expansion
  - MercenaryBelt #Coyote: Pirate Loadout Expansion
  - PilotEars
  - ContractorEncryptionKey
  - ContractorBoxSurvival
  - SmugglerPDA
  - ContractorWallet
  - ContractorCartridge
  - ContractorBackpackItems
  - ContractorHandItems
  - ContractorInstruments
  - NFSpeciesSpecific
  canCustomizeName: true # pseudonym?
