# sexcretary: STC, but cuter and does more stuff or something
- type: job
  id: Secretary
  name: job-name-secretary
  description: job-description-secretary
  playTimeTracker: JobSecretary
  startingGear: SecretaryGear
  alwaysUseSpawner: true
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72000 # 20 hrs
  - !type:RoleTimeRequirement
    role: JobHeadOfPersonnel # frontier: JobSecurityGuard -> CS: JobHeadOfPersonnel
    time: 3600 # frontier: 3 hrs as security guard -> CS: 1 hr of itself
  whitelisted: true
  canBeAntag: false
  icon: "JobIconStc"
  supervisors: job-supervisors-sr
  weight: 160
  displayWeight: 50 # Second from the top
  setPreference: true
  accessGroups:
  - AllAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddRpiAuraSpecial
    aurasToAdd:
    - rpiAuraStationDutchess
  - !type:AddRpiJobModifierSpecial
    modifiersToAdd:
    - rpiJobModifierStationDutchess
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
- type: startingGear
  id: SecretaryGear
  equipment:
    id: SecretaryPDA
  storage:
    back:
    - Flash
    - RubberStampSecretary
    - EncryptionKeyStationMaster
    - ShipVoucherFrontierSecretary
  encryptionKeys:
  - BoxFolderSr

- type: playTimeTracker
  id: JobSecretary

- type: chameleonOutfit
  id: SecretaryChameleonOutfit
  job: Secretary
  equipment:
    head: ClothingHeadHatSecretaryCap

- type: entity
  parent: ShipVoucherFrontierJanitor
  id: ShipVoucherFrontierSecretary
  name: station secretary ship voucher
  description: Allows for one free tug ship purchase from the Frontier Staff Shipyard. Destroyed on sale.
  components:
  - type: Sprite
    layers:
    - state: generic
    - state: voucherstationtrafficcontroller
  - type: ShipyardVoucher
    access:
    - StationTrafficController

