- type: job
  id: PublicAffairsLiaison
  name: job-name-pal
  description: job-description-public-affairs-liaison
  playTimeTracker: JobPublicAffairsLiaison
  requirements: # Coyote editted the playtime required for Sergeant
  - !type:OverallPlaytimeRequirement
    time: 108000 # 30 hours
  - !type:DepartmentTimeRequirement
    department: Security
    time: 86400 # 24 hours
  startingGear: PublicAffairGear
  icon: "JobIconPublicAffairsLiaison"
  supervisors: job-supervisors-cadet
  canBeAntag: false
  weight: 105
  displayWeight: 16
  access: # Access was editted by Coyote
  - HeadOfSecurity
  - Command
  - Armory
  - Sergeant
  - Bailiff
  - Brigmedic
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PublicAffairGear
  equipment:
    pocket1: NFHyperlinkBookSpaceLaw
    pocket2: BoxFolderClipboardPal
  storage:
    back:
    - Flash
    - BoxFolderPalBrown
    - BoxFolderNfsdForms
    - RubberStampPal
    - EncryptionKeyCommand

- type: chameleonOutfit
  id: PublicAffairsLiaisonChameleonOutfit
  job: PublicAffairsLiaison
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
